name: Run parser

on:
  push:
  pull_request:

jobs:
  tests:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true

      - name: Sync dependencies
        run: rye sync

      - name: Run ANTLR
        run: antlr4 -Dlanguage=Python3 project/task11/parser/Graph.g4
