name: Run tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install rye
        uses: eifinger/setup-rye@v4
        with:
          enable-cache: true

      - name: Sync dependencies
        run: |
          source .venv/bin/activate
          rye sync

      - name: Use ANTLR
        run: antlr4 -Dlanguage=Python3 project/task11/parser/Graph.g4

      - name: Run tests
        run: python scripts/run_tests.py
